server:
  port: 9090
spring:
  application:
    name: mcp-client-server-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_database?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 112427
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen2.5:7b

