server:
  port: 10000
spring:
  application:
    name: mcp-client-server-demo
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: sk-882e9574080f46aba62969e5655b26cf
      chat:
        options:
          model: qwen-plus
      embedding:
        options:
          model: text-embedding-v3
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen2.5:7b
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.ustc.myy.ragdemo: debug

